name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk
        sudo apt-get install -y build-essential
        sudo apt-get install -y cmake
        sudo apt-get install -y autotools-dev autoconf automake libtool pkg-config
        sudo apt-get install -y wget unzip
    - name: Install Android SDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        mkdir -p ~/.android-sdk/cmdline-tools
        mv cmdline-tools ~/.android-sdk/cmdline-tools/latest
        export ANDROID_HOME=~/.android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"
    - name: Install Python dependencies
      run: |
        pip install buildozer
        pip install Cython
        pip install setuptools
    - name: Build APK
      run: |
        export ANDROID_HOME=~/.android-sdk
        buildozer android debug
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: brawl-math.apk
        path: bin/*.apk
